 repos:
  - repo: local
    hooks:
      - id: django-test
        name: django-test
        entry: python manage.py test
        always_run: true
        pass_filenames: false
        language: system

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
