repos:
#-   repo: https://github.com/pre-commit/pre-commit-hooks
#    rev: v2.3.0
#    hooks:
#    -   id: flake8
#    -   id: django-test

- repo: local

  hooks:
    - id: flake8
      name: flake8
      entry: flake8
      language: system
      types: [python]

    - id: django-test
      name: django-test
      entry: python manage.py test
      always_run: true
      pass_filenames: false
      language: system


#repos:
#-   repo: https://github.com/pre-commit/pre-commit-hooks
#    rev: v2.3.0
#    hooks:
#    -   id: flake8
#    -   id: django-test
#
#-   repo: https://github.com/pycqa/flake8
#    rev: 5.0.0
#    hooks:
#    -   id: flake8
#
