version: "3.9"

services:
    web:
        image: levelup_app:latest
        command: >
          bash -c "python /code/manage.py migrate
          && python /code/manage.py create_superuser
          && python manage.py runserver 0.0.0.0:8000"

        volumes:
          - .:/code
        ports:
          - 8000:8000
        depends_on:
          - db
    db:
        image: postgres
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        environment:
          - CELERY_BROKER=redis://redis:6379/0
          - CELERY_BACKEND=redis://redis:6379/0
          - POSTGRES_HOST_AUTH_METHOD=trust
    celery:
        build: .
        command: celery -A levelup worker -l debug -P gevent
        volumes:
          - .:/code
        environment:
          - DEBUG=1
          - CELERY_RESULT_EXTENDED = True
          - CELERY_BROKER=redis://redis:6379/0
          - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
          - web
          - redis
          - db
    celery-beat:
      build: .
      command: celery -A levelup beat
      depends_on:
        - db
        - redis
    redis:
        image: "redis:latest"

volumes:
  postgres_data: