# Generated by Django 3.2.16 on 2023-01-11 16:52

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(db_index=True, max_length=100)),
                ('date_create', models.DateTimeField(auto_now=True)),
                ('date_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductListCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=100)),
                ('date_create', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=product.models.document_path_and_name)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_no', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('r_state', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, choices=[('TV', 'TV set'), ('MOBILE', 'Mobile Phone'), ('AUDIO', 'Audio system'), ('PHOTO', 'Photo camera')], max_length=20, null=True)),
                ('qty', models.CharField(default=1, max_length=100)),
                ('order', models.ManyToManyField(related_name='products', to='product.Order', verbose_name='Order')),
            ],
        ),
    ]
