# Generated by Django 3.2.16 on 2023-01-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_no',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
