# Generated by Django 3.2.16 on 2023-02-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_product_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_no',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
